version: 2.1
executors:
  test:
    docker:
      - image: circleci/golang:1.15

jobs:
  test:
    executor:
      name: test
    environment:
      TEST_RESULTS: /tmp/test-results
    working_directory: ~/workspace
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - run: go get -u github.com/jstemmer/go-junit-report
      - run: |
          go test -v -race -cover -coverprofile=/tmp/cover.out -covermode=atomic ./... | go-junit-report -set-exit-code=true > ${TEST_RESULTS}/go-test-report.xml
          go tool cover -html=/tmp/cover.out -o /tmp/cover.html
      - store_artifacts:
          path: /tmp/cover.html
          destination: coverage
      - store_test_results:
          path: /tmp/test-results

workflows:
  version: 2
  test:
    jobs:
      - test:
          name: test
